version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./.docker/tmp/zookeeper:/var/lib/zookeeper/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions"
    volumes:
      - ./.docker/tmp/kafka:/var/lib/kafka/data

  payment-wallet-db:
    container_name: payment-wallet-db
    image: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadminpassword
    volumes:
      - ./.docker/tmp/mongo:/var/lib/mongodb/data
  payments-wallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments-wallet-api
    restart: unless-stopped
    ports:
      - '4000:4000'
    depends_on:
      - zookeeper
      - kafka
      - payment-wallet-db
    environment:
      NODE_ENE: development
      DATABASE_NAME: payment-wallet-api
      DATABASE_PASS: mongoadminpassword
      DATABASE_USER: mongoadmin
      DATABASE_URL: mongodb://payment-wallet-db:27017
      JWT_SECRET: payment-wallet-api-secret
      KAFKA_BROKER_URL: kafka:9092
      KAFKA_CLIENT_ID: payment-wallet-api
      KAFKA_GROUP_ID: payment-wallet-api-group
      KAFKA_SESSION_TIMEOUT_MS: 45000
      KAFKA_CONSUMER_SESSION_TIMEOUT_MS: 30000